name: last_fm_api
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #UI
  shimmer: ^2.0.0
  flutter_swiper: ^1.1.6
  infinite_scroll_pagination: ^3.1.0
  flutter_html: ^2.1.5
  flutter_screenutil: ^5.0.0+2
  transparent_image: ^2.0.0

  #JSON & NETWORK
  json_annotation: ^4.3.0
  quiver: ^3.0.1+1
  dio: ^4.0.3
  freezed: ^1.0.0

  #STATE MANAGEMNT
  get: ^4.3.8

  #TOOLS
  intl: ^0.17.0
  url_launcher: ^6.0.15
  flavor: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #json model generatior
  json_to_model: ^3.0.1
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
